### ISSUE TITLE
requireTrailingComma: false, if there preset

### ISSUE THREAD

**Issue by Gurylev** [jscs-dev/node-jscs#1711] opened 2015-08-21 04:35 UTC
I want set parameter "requireTrailingComma": false, when "preset", this parameter true, but reports an error. This applies to all objects.

```requireTrailingComma option ignoreSingleLine requires true value or should be removed```

**Comment by Gurylev** [comment] 2015-08-21 04:36
The docs stated "Boolean"

**Comment by zxqfox** [comment] 2015-08-21 05:21
Just set it to null instead of false.

http://jscs.info/overview.html
> You can specifically disable any preset rule by creating a .jscsrc config file and assigning it to null, like so:

Would be great if you know how to improve docs ;-)

**Comment by hzoo** [comment] 2015-08-21 20:11
If they use a preset then the option maybe should say to allow null to disable (or we allow `false` eventually which I think we talked about a bit)

**Comment by magicdawn** [comment] 2015-08-24 06:14
@hzoo Both are good~

of which `allow false` maybe better & straighter

**Comment by hzoo** [comment] 2015-08-24 16:27
We can add a new issue to discuss adding `false` as an option.

**Comment by Gurylev** [comment] 2015-08-25 04:47
But my question was about the "false"...

**Comment by hzoo** [comment] 2015-08-25 11:36
Sorry I had meant supporting false in all rules in general

**Comment by markelog** [comment] 2015-08-25 13:58
Duplicate of https://github.com/jscs-dev/node-jscs/issues/1342

**Closed by markelog** 2015-08-25 13:58 UTC
Labels: question
