### ISSUE TITLE
disallowCommaBeforeLineBreak Problem with function params

### ISSUE THREAD

**Issue by Mykhail** [jscs-dev/node-jscs#2012] opened 2015-12-08 14:56 UTC
With the disallowCommaBeforeLineBreak rule set to true, jscs tells me that there is a style error with a comma after function params. 

"Commas should be placed on new line at ..."

see the following screenshots:

![image](https://cloud.githubusercontent.com/assets/4948238/11658652/6584903e-9dcc-11e5-942e-9f8a981e3a49.png)

![image](https://cloud.githubusercontent.com/assets/4948238/11658660/6cd5108e-9dcc-11e5-806b-0f51141e4954.png)

**Comment by Sjeiti** [comment] 2016-04-02 21:01
The problem is this assertion: https://github.com/jscs-dev/node-jscs/blob/99bdf4f7240110a30ff223fcebcca4868bcdb4e3/lib/rules/disallow-comma-before-line-break.js#L119-L123
I don't think it should be part of this rule. **disallowCommaBeforeLineBreak** implies commas are not allowed at the end of a line. So commas should be allowed everywhere else.

**Comment by markelog** [comment] 2016-05-19 18:25
At this point only major and CST related bugs will be fixed.

**Closed by markelog** 2016-05-19 18:25 UTC
Labels: bug
