### ISSUE TITLE
requireLineFeedAtFileEnd not throwing error?

### ISSUE THREAD

**Issue by benjamincharity** [jscs-dev/node-jscs#1568] opened 2015-07-27 11:50 UTC
Recently made the switch to JSCS and really enjoying it so far!

I have noticed that with `requireLineFeedAtFileEnd` set to `true`, no error is surfaced when there is no empty line at the end of my JS file. Am I misinterpreting this rule?

```
// This should throw an error

    // file contents above...
}); // end of file with no blank line
```

```
// This should be valid

    // file contents above...
});
    // empty line here to end file
```

**Comment by mrjoelkemp** [comment] 2015-07-28 03:14
Hey @benjamincharity. Thanks for reporting. 

Any chance you could specify your jscs version (I assume it's 1.13 if you just made the switch to jscs) and a brief snippet of code that reproduces the error?

Thanks in advance.

**Comment by benjamincharity** [comment] 2015-07-28 10:29
@mrjoelkemp yep I'm on `1.13.1`. 

Code that should be throwing an error:

```
(function() {
    console.log('Hello World');
})();
// this is a blank line at the end of the document
```

I'll also post my full `.jscsrc` in case I incorrectly formatted something.

```
{
    "disallowEmptyBlocks": true,
    "disallowIdentifierNames": [
        "temp",
        "foo",
        "bar",
        "dev"
    ],
    "disallowImplicitTypeConversion": [
        "numeric",
        "boolean",
        "binary",
        "string"
    ],
    "disallowKeywordsOnNewLine": [
        "else"
    ],
    "disallowMixedSpacesAndTabs": true,
    "disallowMultipleLineStrings": true,
    "disallowMultipleVarDecl": "strict",
    "disallowNamedUnassignedFunctions": true,
    "disallowNewlineBeforeBlockStatements": true,
    "disallowOperatorBeforeLineBreak": [
        "."
    ],
    "disallowQuotedKeysInObjects": true,
    "disallowSpaceAfterObjectKeys": true,
    "disallowSpaceAfterPrefixUnaryOperators": [
        "++",
        "--",
        "+",
        "-",
        "~",
        "!"
    ],
    "disallowSpaceBeforePostfixUnaryOperators": [
        "++",
        "--"
    ],
    "disallowSpacesInAnonymousFunctionExpression": {
        "beforeOpeningRoundBrace": true
    },
    "disallowSpacesInCallExpression": true,
    "disallowSpacesInFunctionDeclaration": {
        "beforeOpeningRoundBrace": true
    },
    "disallowSpacesInFunction": {
        "beforeOpeningRoundBrace": true
    },
    "disallowSpacesInNamedFunctionExpression": {
        "beforeOpeningRoundBrace": true
    },
    "disallowSpacesInsideBrackets": {
        "allExcept": [ "[", "]" ]
    },
    "disallowSpacesInsideParentheses": true,
    "disallowTrailingComma": true,
    "disallowTrailingWhitespace": true,
    "disallowYodaConditions": true,
    "maximumLineLength": {
        "value": 100,
        "tabSize": 4,
        "allowComments": false,
        "allowUrlComments": true,
        "allowRegex": false
    },
    "requireBlocksOnNewline": true,
    "requireCamelCaseOrUpperCaseIdentifiers": "ignoreProperties",
    "requireCapitalizedConstructors": true,
    "requireCommaBeforeLineBreak": true,
    "requireCurlyBraces": [
        "if",
        "else",
        "for",
        "while",
        "do",
        "try",
        "catch"
    ],
    "requireDotNotation": true,
    "requireFunctionDeclarations": true,
    "requireLineBreakAfterVariableAssignment": true,
    "requireLineFeedAtFileEnd": true,
    "requireOperatorBeforeLineBreak": [
        "?",
        "=",
        "+",
        "-",
        "/",
        "*",
        "==",
        "===",
        "!=",
        "!==",
        ">",
        ">=",
        "<",
        "<="
    ],
    "requirePaddingNewLineAfterVariableDeclaration": true,
    "requirePaddingNewLinesAfterBlocks": {
        "allExcept": [
            "inCallExpressions",
            "inArrayExpressions",
            "inProperties"
        ]
    },
    "requirePaddingNewLinesAfterUseStrict": true,
    "requirePaddingNewLinesBeforeExport": true,
    "requirePaddingNewlinesBeforeKeywords": [
        "do",
        "for",
        "if",
        "switch",
        "case",
        "try",
        "catch",
        "void",
        "with",
        "return",
        "typeof",
        "function"
    ],
    "requirePaddingNewLinesBeforeLineComments": {
        "allExcept": "firstAfterCurly"
    },
    "requirePaddingNewLinesInObjects": true,
    "requireParenthesesAroundIIFE": true,
    "requireSemicolons": true,
    "requireSpaceAfterBinaryOperators": [
        "=",
        ",",
        "+",
        "-",
        "/",
        "*",
        "==",
        "===",
        "!=",
        "!=="
    ],
    "requireSpaceAfterKeywords": [
        "do",
        "for",
        "if",
        "else",
        "switch",
        "case",
        "try",
        "catch",
        "void",
        "while",
        "with",
        "return",
        "typeof"
    ],
    "requireSpaceAfterLineComment": true,
    "requireSpaceBeforeBinaryOperators": [
        "=",
        "+",
        "-",
        "/",
        "*",
        "==",
        "===",
        "!=",
        "!=="
    ],
    "requireSpaceBeforeBlockStatements": true,
    "requireSpaceBeforeKeywords": [
        "else",
        "while",
        "catch"
    ],
    "requireSpaceBeforeObjectValues": true,
    "requireSpaceBetweenArguments": true,
    "requireSpacesInAnonymousFunctionExpression": {
        "beforeOpeningCurlyBrace": true
    },
    "requireSpacesInConditionalExpression": {
        "afterConsequent": true
    },
    "requireSpacesInForStatement": true,
    "requireSpacesInFunctionDeclaration": {
        "beforeOpeningCurlyBrace": true
    },
    "requireSpacesInFunctionExpression": {
        "beforeOpeningCurlyBrace": true
    },
    "requireSpacesInFunction": {
        "beforeOpeningCurlyBrace": true
    },
    "requireSpacesInNamedFunctionExpression": {
        "beforeOpeningCurlyBrace": true
    },
    "validateIndentation": 4,
    "validateLineBreaks": "LF",
    "validateParameterSeparator": ", ",
    "validateQuoteMarks": "'",
    "excludeFiles": [
        "node_modules/**",
        "bower_components/**",
        "dist/**",
        "e2e/**",
        "typings/**",
        ".tmp/**"
    ]
}
```

**Comment by mrjoelkemp** [comment] 2015-07-29 01:26
The following tests passes:

![image](https://cloud.githubusercontent.com/assets/865203/8947904/d5f64a18-356e-11e5-8b01-da4e22e453a4.png)

![image](https://cloud.githubusercontent.com/assets/865203/8947927/1866c7ec-356f-11e5-8fa2-444838c43c08.png)

I don't see anything glaringly wrong with your config either. I'm going to close this issue since the test shows that the rule is catching that case. 

Perhaps someone else can provide insight into what might be going wrong. Let me know if you find anything. Happy to reopen if it's a legit bug with the rule.

**Closed by mrjoelkemp** 2015-07-29 01:26 UTC

**Comment by benjamincharity** [comment] 2015-08-05 12:20
So no one has any ideas on this? This is reproducible issue across my team; if it was just my machine I'd assume it was just me...

**Comment by mrjoelkemp** [comment] 2015-08-06 02:21
@benjamincharity hurray! glad to hear it.
