### ISSUE TITLE
jscs --auto-configure . process out of memory

### ISSUE THREAD

**Issue by khaledkbadr** [jscs-dev/node-jscs#1501] opened 2015-06-30 08:52 UTC
When I run jscs --auto-configure . I get 
Checking . against the presets
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
Aborted (core dumped)

in my 8 GB RAM laptop

**Comment by mrjoelkemp** [comment] 2015-06-30 13:14
Hey @khaledkbadr. Thanks for reporting.

Can you try `jscs --max-old-space-size=4096 --auto-configure .`? That'll increase node's memory limit from 512mb to 4gb. That should be enough to avoid the error.

**Comment by mrjoelkemp** [comment] 2015-06-30 13:18
See http://stackoverflow.com/a/26094800/700897 for more info. 

We haven't had to care much about memory concerns for parsing really big files. An alternative concern could be a memory leak in the auto-config generator, but that's hard to say with just this one reported case.

**Comment by chinchang** [comment] 2015-07-01 11:48
@mrjoelkemp I get an error when using that flag: 
`error: unknown option `--max-old-space-size'`

```
» jscs --version
1.13.1
```

**Comment by mrjoelkemp** [comment] 2015-07-01 13:39
Makes sense, but odd that I didn't see that error locally. You could get
around this doing something like node --max-old-space-size=4096
./node_modules/jscs/bin/jscs --auto-configure .

I'm more interested in finding out how to avoid the space issue on the jscs
side. It's hard to dig in without a reproducible scenario though. I'd only
be guessing at possible causes at this point.

Let me know if that works.

**Comment by mikesherov** [comment] 2015-07-01 20:22
@khaledkbadr can you point us to a public repo that this fails on? If we had a repro case, we could debug this much faster.

@mrjoelkemp we may what to try the v8 profiler to see if we can detect a memory leak. tutorial here: https://github.com/felixge/node-memory-leak-tutorial

**Comment by khaledkbadr** [comment] 2015-07-02 01:42
I have a very initial rep that I had the same problem with. 
https://github.com/khaledkbadr/token-authentication

Does jscs jscs --auto-configure . ignore the node_modules directory??

**Comment by mrjoelkemp** [comment] 2015-07-02 02:09
It should on the master branch given a recent commit. Can you try the
master branch and see if that helps?

**Comment by mrjoelkemp** [comment] 2015-07-05 18:35
Closing as I think 1ba4b45d649729670edf691f9971e38011a8bcdb fixes the problem. Happy to reopen if that's not the case.

**Closed by mrjoelkemp** 2015-07-05 18:35 UTC

**Comment by mikedaly** [comment] 2015-10-13 17:14
FWIW, commit `1ba4b45` does not address the issue for me. It fails with that error when trying to auto-configure our product's source folder, which does not have node_modules or bower_components (both of which should probably be ignored by default, not just node_modules).

If I start node using the `--max-old-space-size=4096` argument as described above, then it does work correctly.

**Comment by kirbysayshi** [comment] 2016-02-09 00:34
I'm guessing this is the same issue as #2124. This OOM condition was _probably_ more likely before the automatic exclusion of `node_modules` in 1ba4b45...

**Comment by KeithPepin-MW** [comment] 2016-12-19 16:15
I was working fine without issue until I added istanbul to my project and jscs began complaining about perceived errors in the ./coverage directory it created.  I added "excludeFiles": ["coverage/**"] to my .jscsrc so this would no longer get checked and ran smack into the memory problems mentioned above.    Adding the --max-old-space-size=4096 flag mentioned above does NOT correct the problem for me.

**Comment by KeithPepin-MW** [comment] 2016-12-19 16:37
Update:  I think once I added the `excludeFiles` parameter, `node_modules` and `.git` folders may have been included again.  Adding them to the `excludeFiles` array of paths fixed the problem for me.

**Comment by KeithPepin-MW** [comment] 2017-01-27 22:04
Any update on this issue?  Now seeing problems where jscs simply hangs when running our Travis builds.

**Comment by mikedaly** [comment] 2017-01-27 22:08
You aren't likely to see any updates here, since JSCS is now a deprecated project. The committers have moved over to ESLint and recommended that we do the same.

[JSCS — end of the line](https://medium.com/@markelog/jscs-end-of-the-line-bc9bf0b3fdb2#.3qrw9jwnz)

**Comment by KeithPepin-MW** [comment] 2017-01-27 22:19
Thanks Mike - I hadn't realized that.  I'll make the switch over to eslint.
