### ISSUE TITLE
requireSafeContextKeyword to enforce use of safeContextKeyword

### ISSUE THREAD

**Issue by smeijer** [jscs-dev/node-jscs#1216] opened 2015-03-29 14:12 UTC
Would be great if the use of a "safeContextKeyword" could be enforced. Maybe even with a setting to allow the use based on the function line count?

---
.jscsrc
```json
{ 
  "safeContextKeyword": ["self"],
  "requireSafeContextKeyword": true
}
```

valid:
```js
var obj = {
  // ...
  func: function() {
    var self = this;
    self.foo = 'bar';
  }  
}
```

invalid:
```js
var obj = {
  // ...
  func: function() {
    var self = this;
    this.foo = 'bar'; // usage of `this` is disallowed, use the safe context keyword
  }  
}
```
---
.jscsrc
```json
{ 
  "safeContextKeyword": ["self"],
  "requireSafeContextKeyword": "allButTinyPredicates"
}
```

valid:
```js
var obj = {
  // ...
  func: function() {
    var self = this;
    self.foo = 'bar';
  },

  func2: function() {
    return this.func(); // valid now, because the method has less than two lines;
  },

  equals: function(val) { 
    return this.foo === val; // valid now, because the method has less than two lines;
  }
}

**Comment by mrjoelkemp** [comment] 2015-03-29 15:48
Thanks for contributing @smeijer. This proposal sounds like a great candidate for a custom plugin. Unless others chime in on this PR, I'd vote for it not being in core.

By using `safeContextKeyword`, you're already enforcing that it's used (when needed). Your proposal would also have to ban use of `.bind(this)` if I understand correctly.

I'll wait for the opinions of other contributors before closing this issue.

cc @hzoo @TheSavior @alawatthe

**Comment by smeijer** [comment] 2015-03-29 16:32
Bind would not necessarily be banned. However the use of ```this``` will be for most part.

```js
function () {
  var self = this;
  return self.color;
}.bind(car);
```

```js
function parent () {
  var self = this;

  var child = function () {
    var self = this;
    return self.foo;
  }.bind(self);
}
```

The idea is to limit the usage of ```this```, as it is a lot harder to trace the context of ```this```, than the context of a property you've named yourself. You're not really enforcing such a thing by using ```safeContextKeyword```. You're only enforcing that the context is given a certain property name when the developer is binding the context to a defined property.

For example ```"safeContextKeyword": ["self"]``` is not forbidding anything in the snippet below:
```js
myObj = (function () {
  var self = this;

  self.foo = 'Foo';
  this.bar = 'Bar'; // this should be a problem, property should be referenced as 'self.bar'

  var instance = {
    baz: 'Baz',

    getFoo: function () {
      return this.foo; // an error should be highlighted here, possible unwanted context change
    },

    getBar: function () {
      return self.bar; // this one is ok
    },

    getBaz: function () {
      var self = this; // switch context explicitly
      return self.baz; // a property of 'instance'
    }
  };

  return instance;
}());

myObj.getFoo(); // returns undefined
myObj.getBar(); // returns 'Bar'
myObj.getBaz(); // returns 'Baz'
```

**Comment by alawatthe** [comment] 2015-03-30 17:45
I agree with @mrjoelkemp that this should be a custom plugin, since it is a kind of special coding style. I don't want to criticize your (@smeijer) coding style in any way, I just never had problems, not knowing what ```this``` refers to. Furthermore, with the rise of arrow functions in ES6 the need to bind ```this``` or the use of a safe context keyword will decrease a lot, making the stuff around ```this``` a lot clearer. So requiring the use of a safe context keyword feels a bit weird.

On a site note: Not knowing what ```this```refers to might be caused by code which is too complicated. So this might indicate the need for refactoring. In this light, requiring a save context keyword feels a bit like trying to fight the result (not knowing what ```this``` refers to) and not the cause (complicated code).

**Comment by mikesherov** [comment] 2015-03-30 19:24
I agree @mrjoelkemp. This is definitely a plugin. @smeijer thanks for the feedback. I'm going to close this now. Let me know if you disagree.

**Closed by mikesherov** 2015-03-30 19:24 UTC
Labels: enhancement, new rule
