### ISSUE TITLE
rule requireMultipleVarDecl: true crashes jscs cli

### ISSUE THREAD

**Issue by hacker112** [jscs-dev/node-jscs#1163] opened 2015-03-11 14:04 UTC
When I have the following .jscs.json file:
```json
{
    "requireMultipleVarDecl": true
}
```

And run the commandline tool, I get an TypeError: 

```
$ jscs --version
1.11.3
$ jscs .
TypeError: Cannot read property 'type' of undefined
    at /usr/local/lib/node_modules/jscs/lib/rules/require-multiple-var-decl.js:41:24
    at Array.forEach (native)
    at Object.JsFile.iterateNodesByType (/usr/local/lib/node_modules/jscs/lib/js-file.js:378:42)
    at Object.consecutive [as _check] (/usr/local/lib/node_modules/jscs/lib/rules/require-multiple-var-decl.js:37:10)
    at Object.module.exports.check (/usr/local/lib/node_modules/jscs/lib/rules/require-multiple-var-decl.js:119:28)
    at null.<anonymous> (/usr/local/lib/node_modules/jscs/lib/string-checker.js:157:22)
    at Array.forEach (native)
    at StringChecker.checkString (/usr/local/lib/node_modules/jscs/lib/string-checker.js:155:35)
    at null.<anonymous> (/usr/local/lib/node_modules/jscs/lib/checker.js:40:25)
    at Array.<anonymous> (/usr/local/lib/node_modules/jscs/node_modules/vow/lib/vow.js:699:39)
```

**Comment by hzoo** [comment] 2015-03-11 14:08
Does it run on a specific file/folder? like `jscs ./file.js`
If you are using ES6 you need `"esnext": true` in the jscs file. You might want to exclude folders like `node_modules` or something.

**Comment by hacker112** [comment] 2015-03-11 14:20
I am not using ES6, and I exclude folders normally, I just made an simplified example above. I found a specific file and simplified it to find the root of the problem. What I found is that a var in switch-case might cause the problem. The following file throws the same exception.

```javascript
function a(b) {
    'use strict';

    switch (b) {
    case 1:
        var problem = 1;
    }
}
```

**Comment by hzoo** [comment] 2015-03-11 22:34
Ok can reproduce! Yeah looks like an issue with the rule. 

```js
var sibling = node.parentCollection[pos + 1];
if (sibling.type ...
```
`sibling is undefined`

**Comment by twolfson** [comment] 2015-04-07 06:56
This seems to be a duplicate of #916. Since this is on the 0.12 milestone and has the "help wanted" label on it, I am going to take a shot at it.

**Comment by twolfson** [comment] 2015-04-07 07:55
That problem was a lot deeper than I expected but I found the cause and submitted the PR. The issue is best explained in the PR itself:

#1243

**Closed** 2015-04-12 16:31 UTC
Labels: bug, help-wanted
