### ISSUE TITLE
Error in yandex preset after upgrade to 1.11.0

### ISSUE THREAD

**Issue by ikokostya** [jscs-dev/node-jscs#1033] opened 2015-02-09 14:46 UTC
This code

```js
var NotificationPanel = inherit(YBlock, /** @lends NotificationPanel.prototype */ {
});
```

works in 1.10.0 version

```
[kostya@arch test]$ ./node_modules/.bin/jscs --version
1.10.0
[kostya@arch test]$ ./node_modules/.bin/jscs test.js 
No code style errors found.

```

but doesn't work in 1.11.0

```
[kostya@arch test]$ ./node_modules/.bin/jscs --version
1.11.0
[kostya@arch test]$ ./node_modules/.bin/jscs test.js 
1 spaces required between , and { at test.js :
     1 |var NotificationPanel = inherit(YBlock, /** @lends NotificationPanel.prototype */ {
-----------------------------------------------^
     2 |});
     3 |


1 code style error found.
```

**Comment by mikesherov** [comment] 2015-02-09 14:55
This is a dupe of #1025 and will be patched shortly! Thanks again.

**Closed by mikesherov** 2015-02-09 14:55 UTC
