### ISSUE TITLE
React - Decorator - class ES2015

### ISSUE THREAD

**Issue by thomashermant** [jscs-dev/node-jscs#2147] opened 2016-02-26 15:10 UTC
Hi everyone,

Since I add parameters to my decorator (high order component)
@withOwn(**'media', ['user_id']**)
class MediaEdit extends React.Component { ... }

I see this error (stack trace below)

------------------------------

WARNING in ./app/views/MediaEdit/MediaEdit.jsx
jscs results in errors
  internalError @ line 1 char 0
    Error running rule validateQuoteMarks: This is an issue with JSCS and not your codebase.
Please file an issue (with the stack trace below) at: https://github.com/jscs-dev/node-jscs/issues/new

TypeError: Cannot read property 'type' of null
    at /Users/tom/Desktop/nh/node_modules/jscs/lib/rules/validate-quote-marks.js:118:63
    at /Users/tom/Desktop/nh/node_modules/jscs/lib/js-file.js:614:17
    at Object.JsFile._forEachToken (/Users/tom/Desktop/nh/node_modules/jscs/lib/js-file.js:651:13)
    at Object.JsFile.iterateTokensByType (/Users/tom/Desktop/nh/node_modules/jscs/lib/js-file.js:612:14)
    at Object.module.exports.check (/Users/tom/Desktop/nh/node_modules/jscs/lib/rules/validate-quote-marks.js:115:14)
    at null.<anonymous> (/Users/tom/Desktop/nh/node_modules/jscs/lib/string-checker.js:165:22)
    at Array.forEach (native)
    at StringChecker._checkJsFile (/Users/tom/Desktop/nh/node_modules/jscs/lib/string-checker.js:161:31)
    at StringChecker.checkString (/Users/tom/Desktop/nh/node_modules/jscs/lib/string-checker.js:106:14)
    at Object.checkSource (/Users/tom/Desktop/nh/node_modules/jscs-loader/index.js:91:24)
    at Object.<anonymous> (/Users/tom/Desktop/nh/node_modules/jscs-loader/index.js:140:19)
    at /Users/tom/Desktop/nh/node_modules/jscs-loader/index.js:62:7
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)

Best regards,
Thomas

**Comment by hzoo** [comment] 2016-02-26 15:34
@markelog Need to account for null parent? https://github.com/jscs-dev/node-jscs/blob/2.x/lib/rules/validate-quote-marks.js#L118

**Comment by markelog** [comment] 2016-02-26 15:43
Yeah, sounds like an easy fix

**Comment by Skywalker13** [comment] 2016-02-27 12:57
duplicate of #2141

**Comment by markelog** [comment] 2016-02-27 23:22
Indeed

**Closed by markelog** 2016-02-27 23:22 UTC
Labels: esnext
