### ISSUE TITLE
svg logo

### ISSUE THREAD

**Issue by alawatthe** [jscs-dev/node-jscs#899] opened 2015-01-11 12:56 UTC
Since the .png logo on the website looks a little blurry on retina displays, [I recreated it in SVG](http://codepen.io/anon/pen/pvRxYQ).
I tried to match the .png logo as closely as possibly. But didn't know what font was used in the .png logo, so I used the "J" and "S" from the [logo.js project](https://github.com/voodootikigod/logo.js/blob/master/js.svg). The "C" is hacked together by myself.
As colors I used #00000 and #eada5b, which I colorpicked from the png version.

The code still needs more clean up, but what do you think in general?

**Comment by mrjoelkemp** [comment] 2015-01-12 04:52
That's sooo cool @alawatthe. Awesome job. 

Would you be able to vertically center the logo? The top has a padding of ~85px whereas the bottom has a padding of ~110px. 

You'll likely have to modify https://github.com/jscs-dev/jscs-dev.github.io/blob/dev/src/partials/header.jade to integrate the logo.

**Comment by mdevils** [comment] 2015-01-12 11:45
Awesome!!

**Comment by hzoo** [comment] 2015-01-12 13:32
looks great

**Comment by alawatthe** [comment] 2015-01-26 21:04
Here is the new version of the logo. I took some artistic freedom (see below for a comparison). 

When I was done, I found the discussion about the logo and a high res version on the mailing list :-/
But since the SVG version is a lot smaller then the high res version, I think we should use the SVG version.

List of changes:

* everything is aligned to a square grid with 6x6 cells. See below for a screenshot with including the grid. Everything which appears to have the same size has the same size. This resulted in the changes:
	* There is now the same amount of white space (or yellow space?) above and below the text. Addresses your wish @mrjoelkemp.
	* This moves the letters a bit
* The dashes under the J and S were a little bit to short in my opinion, so I made them longer
* color changes (I aligned the colors with the high res version, not the one found on the web site)
	* yellow from #eada5b to #ebdc50
	* black from #00000 to #363633

I hope are ok with my changes and you like it. If there are no further suggestions, I'll create a pull request.


![logo](https://cloud.githubusercontent.com/assets/901391/5908213/cd249bdc-a5a5-11e4-94ab-f8e289f02392.png)

The plot with the grid. The green boxes are used for kerning
![guides](https://cloud.githubusercontent.com/assets/901391/5908222/e86ae310-a5a5-11e4-91ef-56c61d2ad92d.png)

The green letters are the SVG letters, the black ones are from the high res version. 
![comparison](https://cloud.githubusercontent.com/assets/901391/5908296/73baa464-a5a6-11e4-9de4-6c381a3d5b1a.png)

Additionally I recreated the favicon in SVG. The shapes of the dashes and caret are the same as in the logo, just scaled by a factor of 2.
![dashes](https://cloud.githubusercontent.com/assets/901391/5908328/bffb400e-a5a6-11e4-8eb7-90e7a6feed29.png)

**Comment by mikesherov** [comment] 2015-01-26 22:23
:+1:

**Comment by markelog** [comment] 2015-01-27 00:55
> When I was done, I found the discussion about the logo and a high res version on the mailing list :-/

Ask next time, we could save so time :-).

Not gonna feel comfortable with this, until author of logo could check it out.

**Comment by panoplied** [comment] 2015-01-27 13:29
It's cool that some of my arrangement bugs are fixed. And I would like to give some tips. The font used in the original logo is "Neutra Text Bold", which is also used in logo.js as I know. It is used with the default optical kerning option in Photoshop and with increased spacing. And I think that it really asked for some custom grid arrangement. The colors at first stage are meant to be picked from the original logo.js SVG, but now it doesn't seem necessary. And also there is an idea of inverted "dark" version of logo.

The thing I disagree with is the dashes. You see, the first version of logo was made with the original "Neutra Text" dashes, which are pretty short by design. So the font itself is meant to have short dashes. It is designed that way. I reconstructed the proportions of the dashes and made the arrow so they are connected in the way shown on this schemes plus a little visual tuning.

![screen shot 2015-01-27 at 16 03 58](https://cloud.githubusercontent.com/assets/1618838/5918965/d03855ee-a63f-11e4-9498-d73956bf8b1c.png)

![screen shot 2015-01-27 at 16 26 34](https://cloud.githubusercontent.com/assets/1618838/5919088/4fa3f134-a641-11e4-98e7-2473be40e3fc.png)

**Comment by alawatthe** [comment] 2015-01-27 15:06
> Ask next time, we could have save you some time :-).

I will :-) But for this time, I don't mind, I found some useful tools for working with SVG.

> Not gonna feel comfortable with this, until author of logo could check it out.

I am completely open to suggestions, I just want to have a SVG version of the logo. The blurry png bugs bugs me every time I'm on [jscs.info](http://jscs.info).

> The font used in the original logo is "Neutra Text Bold", which is also used in logo.js as I know.

Yes, I know. The reason for not using the font's "C" and creating my own, was that Neutra Text Bold is a commercial font. And since JSCS doesn't own a license (I think, as they don't provide a way to use the fonts as webfonts) I didn't want to use the font. That said, Logo.js probably hasn't gotten any problems for using the font, so likely we won't get any either. But I am still not too comfortable about this.

> It is used with the default optical kerning option in Photoshop and with increased spacing. And I think that it really asked for some custom grid arrangement.

Just to make sure, if I understood you correctly: Are you fine with my kerning or do you prefer the Photoshop one?
I don't have Photoshop right now, so if we what to use some specified kerning, someone else has to do it.

> The colors at first stage are meant to be picked from the original logo.js SVG, but now it doesn't seem necessary.

Oh the colors, that was a pain :expressionless:. The Logo.js project is somewhat inconsistent in this point. Some of the colors I found are: 
* #f3df49 and #2e2e2c used by the original logo https://github.com/voodootikigod/logo.js/blob/master/registry.md
* #f7df1e and #000000 used by the svg version of the original logo https://github.com/voodootikigod/logo.js/blob/master/js.svg
*  #ebdc50 and #363633 the high res version of the jscs logo and the SVG version I did.
* ...

I am not a too big fan of using #000000, but apart from that, I don't care.

> And also there is an idea of inverted "dark" version of logo.

It's no problem to create a dark version. But, may I ask when we want to use the dark version?

> The thing I disagree with is the dashes. You see, the first version of logo was made with the original "Neutra Text" dashes, which are pretty short by design. So the font itself is meant to have short dashes. It is designed that way. I reconstructed the proportions of the dashes and made the arrow so they are connected in the way shown on this schemes plus a little visual tuning.

This is interesting. I didn't know that. I'll change the dashes back.

Thanks for the feedback :-D

**Comment by zxqfox** [comment] 2015-01-27 20:06
> The thing I disagree with is the dashes. You see, the first version of logo was made with the original "Neutra Text" dashes

I kept thinking about what's wrong here. Yes! Size of dashed!

**Comment by markelog** [comment] 2015-05-14 12:02
@alawatthe still interested?

**Comment by alawatthe** [comment] 2015-05-15 08:01
Ah I completely forgot this issue :-/

Yes, I am still interested. Unfortunately I don't have Internet right now (writing this on my mobile phone). So it will take a few days to create a pull request.

**Comment by markelog** [comment] 2015-05-16 07:49
Sure thing! I'm glad you on it :-)

**Comment by alawatthe** [comment] 2015-05-20 12:21
I updated the dashes, to use the original size, with the dashes aligned with the grid
![logo](https://cloud.githubusercontent.com/assets/901391/7725161/413d1ba6-fef8-11e4-8c2c-71438f1145d8.png)

I'm my opinion, the dash below the J is to far to the left, so here is a version, where the dash is aligned with the J. (I like this version better but in the end I don't care.)
![logo](https://cloud.githubusercontent.com/assets/901391/7725382/67ee697e-fefa-11e4-9ca5-33a027a3647e.png)


The circumflex is now using the properties @panoplied explained:
![logo](https://cloud.githubusercontent.com/assets/901391/7725239/0410f558-fef9-11e4-9d22-4a3762f83a44.png)

I did not change the colors as well as the position of the letters. Furthermore, I compared the shape of the letters to the [Neutra version](http://www.houseind.com/t/d7b84f) and found out that it is an almost perfect match, so I did not change the shape either.

Are there any other improvement suggestions?
Hope you like it :-D

**Comment by hzoo** [comment] 2015-05-20 12:31
:+1: for 2nd one too

**Comment by markelog** [comment] 2015-05-28 19:12
If no one objects, i'd like to start using this logo. 

@mdevils it seems we need to landed in some repo, site or main one?

@mikesherov, @mrjoelkemp, @zxqfox thoughts?

@panoplied you cool with that?

**Comment by markelog** [comment] 2015-05-29 21:10
@alawatthe could you post new logo in svg?

**Comment by mdevils** [comment] 2015-06-01 14:30
@markelog I think we can put it to the main repo and reuse it at website.

**Comment by panoplied** [comment] 2015-06-01 15:43
I think it's okay.

**Comment by alawatthe** [comment] 2015-06-04 22:07
@panoplied "okay" does not sound to convinced :-/  Please let me know if there is anything I can/should change :-)

I created a pull request here: https://github.com/jscs-dev/jscs-dev.github.io/pull/20

**Comment by markelog** [comment] 2015-06-08 05:45
Okay, cool, new logo is in the house!

@alawatthe congrats!

**Closed by markelog** 2015-06-08 05:45 UTC
