### ISSUE TITLE
v1.11 requireSpaceBeforeObjectValues breaks on esnext syntax

### ISSUE THREAD

**Issue by RoystonS** [jscs-dev/node-jscs#1029] opened 2015-02-09 12:51 UTC
A change to JSCS for v1.11 now breaks on ESNext object syntax such as

```javascript
var myObj = {
  myFunc() {
  }
};
```

The rule is looking for the colon token that's normally present in a combination of ES5 object key + value (e.g. `myFunc: function() {`), but it isn't present in this ES6 syntax, so it ends up calling `js-file#getNextToken` with no token, which blows up with `TypeError: Cannot read property '_tokenIndex' of undefined`.

(It was all fine in v1.10, and still breaks with `esnext:true` specified.)

**Comment by mikesherov** [comment] 2015-02-09 13:12
Thanks for contributing! This is a dupe of a bug that was already fixed. Patch release coming soon.

**Closed** 2015-02-09 13:13 UTC

**Comment by RoystonS** [comment] 2015-02-09 14:03
Ah yes, #1013 - apologies!
