### ISSUE TITLE
requirePaddingNewLineAfterVariableDeclaration false positive

### ISSUE THREAD

**Issue by SimenB** [jscs-dev/node-jscs#1208] opened 2015-03-27 15:20 UTC
This gives error:
```javascript
initialize: function (options) {
    this.model = options.model;
    this.parent = options.parent;
}
```
The following 2 does not
```javascript
initialize: function (options) { // This errors on unused, nothing else
    var model = options.model;
    var parent = options.parent;
}
```
```javascript
initialize: function (options) {
    var model = options.model;
    var parent = options.parent;

    this.model = model;
    this.parent = parent;
}
```

I expect there to be no difference between assigning to the ``this`` object, and a local variable.

EDIT:
Another example
```javascript
initialize: function (options) {
    this.elementNavn = options.elementNavn;
    this.bilde = options.bilde;
    this.stylingview = options.view;
}
```

This only errors on the first line, not the second.

**Comment by SimenB** [comment] 2015-03-29 11:45
I started to look into making a PR for this, but I ended up more confused. In true TDD fashion, I wrote the test first. So this test fails when added to ``specs/rules/require-padding-newline-after-variable-declaration.js``

```javascript
it('should not report if no extra newline is present when assigning to objects', function() {
    assert(checker.checkString('function (opts) {\nthis.a = opts.a;\nthis.b = opts.b;\n}').isEmpty());
});
```

What's weird, is that if I name the function, the test doesn't fail.

```javascript
it('should not report if no extra newline is present when assigning to objects', function() {
    assert(checker.checkString('function f(opts) {\nthis.a = opts.a;\nthis.b = opts.b;\n}').isEmpty());
});
```

The only difference being ``function (opts)`` vs ``function f(opts)``. Does anybody have any idea why naming the function should matter?

**Comment by mikesherov** [comment] 2015-03-30 01:06
@SimenB, thanks for contributing!

```
function (opts) {
  this.a = opts.a;
  this.b = opts.b;
}
```

Is not valid javascript, which is why the test is failing. 

Also, assigning to a property of an object is not a variable declaration, it's an assignment statement. There is a difference, and this rule respects that difference.

Closing this as "not a bug"

**Closed by mikesherov** 2015-03-30 01:06 UTC

**Comment by SimenB** [comment] 2015-03-30 05:00
@mikesherov Oh, yeah, made an error there. But if you look at the OP, you'll see valid valid JS, which this rule reports as a error. That's a copy from our source code, so it works. To get it to work in Chrome console, just assign it.

```javascript
    it('should not report if no extra newline is present when assigning to objects', function() {
        assert(checker.checkString(
            'var o = {\nf: function (opts) {\nthis.a = opts.a;\nthis.b = opts.b;\n}\n}'
        ).isEmpty());
    });
```

**Comment by SimenB** [comment] 2015-03-30 05:10
> Also, assigning to a property of an object is not a variable declaration, it's an assignment statement. There is a difference, and this rule respects that difference.

The original point of this bug was a false positive (before I tried to write a failing test for it :laughing:), so obviously this rule doesn't respect it. ``requirePaddingNewLineAfterVariableDeclaration`` reports a violation on the assignment.

**Comment by SimenB** [comment] 2015-04-03 09:23
@mikesherov minimal test case: https://gist.github.com/SimenB/ac2fe5db1f43ae8ec7a7
