### ISSUE TITLE
Does not play well with blocks

### ISSUE THREAD

**Issue by domenic** [jscs-dev/node-jscs#1328] opened 2015-05-02 01:37 UTC
Consider the following code:

```js
/// some code here

{
  let prototype = NamedNodeMap.prototype;
  while (prototype) {
    for (const name of Object.getOwnPropertyNames(prototype)) {
      reservedNames.add(name);
    }
    prototype = Object.getPrototypeOf(prototype);
  }
}

/// more code here
```

I get the following warnings:

```
One space required before opening brace for block expressions at lib/jsdom/living/attributes.js :
   104 |};
   105 |
   106 |exports.NamedNodeMap = NamedNodeMap;
--------------------------------------------^
   107 |
   108 |{

Newline before curly brace for block statement is disallowed at lib/jsdom/living/attributes.js :
   104 |};
   105 |
   106 |exports.NamedNodeMap = NamedNodeMap;
--------------------------------------------^
   107 |
   108 |{
```

Can we make an exception to allow bare blocks while still requiring such style rules for `if`s etc.?

**Comment by hzoo** [comment] 2015-05-02 02:44
Yeah that sounds good to me.

In `requireSpaceBeforeBlockStatements, disallowNewlineBeforeBlockStatements` we do

```js
file.iterateNodesByType('BlockStatement', function(node) {
```

I guess we could check the `node.parent` and it's type? Don't know if we have a utility method to check for bare blocks since this would be for es6?

**Comment by markelog** [comment] 2015-07-18 21:40
@hzoo do you wanna check this out further?

**Comment by mikesherov** [comment] 2015-07-19 01:20
There are bare block checks in the indentation rule that you could extract.

**Comment by hzoo** [comment] 2015-09-26 13:13
Sorry for the late reply - I tested this again and cannot reproduce with 

```js
{
  "requireSpaceBeforeBlockStatements": true,
  "disallowNewlineBeforeBlockStatements": true
}
```

If that's the correct config

**Comment by hzoo** [comment] 2015-10-20 01:00
Closing since it seems to be fixed (at least on the latest version / 2.0) since I see jsdom is using 1.x

**Comment by domenic** [comment] 2015-10-22 18:13
This is still not fixed. I tried pulling in https://github.com/tmpvar/jsdom/pull/1266 and changing the offending line but I still get

```
Newline before curly brace for block statement is disallowed at lib/jsdom/living/attributes.js :
   106 |};
   107 |
   108 |exports.NamedNodeMap = NamedNodeMap;
--------------------------------------------^
   109 |
   110 |{
```

inside this code:

```js

exports.NamedNodeMap = NamedNodeMap;

{
  let prototype = NamedNodeMap.prototype;
  while (prototype) {
    for (const name of Object.getOwnPropertyNames(prototype)) {
      reservedNames.add(name);
    }
    prototype = Object.getPrototypeOf(prototype);
  }
}

exports.createNamedNodeMap = function (element) {
  const nnm = Object.create(NamedNodeMap.prototype);
  nnm[INTERNAL] = {
    element,
    attributeList: [],
    attributesByNameMap: new Map()
  };
  return nnm;
};
```

**Comment by hzoo** [comment] 2015-10-22 18:38
Oh sorry I tested it and thought it was still a block :disappointed: so I thought it passed. Will make a fix later.

**Closed** 2015-10-24 13:06 UTC
Labels: indentation, new rule value
