### ISSUE TITLE
Autofixing indentation causes misalignment of nested lines

### ISSUE THREAD

**Issue by lsjroberts** [jscs-dev/node-jscs#1248] opened 2015-04-08 17:00 UTC
Apologies if this has already been reported but I couldn't see an existing issue.

```
$ jscs --version
1.12.0
```

Running:

```
$ jscs test.js --fix
```

On:

```js
// test.js
var foo = {
        "bar": {
            "baz": "baz",
            "qux": "qux"
        }
};

```

Result:

```js
var foo = {
    "bar": {
            "baz": "baz",
            "qux": "qux"
        }
};

```

**It correctly fixes line 2 but this then leaves the nested and block closing lines 3 & 4 with incorrect indentation.**

Using this `.jscsrc`:

```json
{
    "disallowEmptyBlocks": true,
    "disallowKeywords": [
        "do"
    ],
    "disallowKeywordsOnNewLine": [
        "else"
    ],
    "disallowMixedSpacesAndTabs": "smart",
    "disallowMultipleLineBreaks": true,
    "disallowNewlineBeforeBlockStatements": true,
    "disallowPaddingNewlinesInBlocks": true,
    "disallowSpaceAfterObjectKeys": true,
    "disallowSpacesInAnonymousFunctionExpression": {
        "beforeOpeningRoundBrace": true
    },
    "disallowSpacesInCallExpression": true,
    "disallowSpacesInFunctionDeclaration": {
        "beforeOpeningRoundBrace": true
    },
    "disallowSpacesInsideArrayBrackets": true,
    "disallowSpacesInsideObjectBrackets": true,
    "disallowSpacesInsideParentheses": true,
    "disallowTrailingComma": true,
    "disallowTrailingWhitespace": true,
    "maximumLineLength": 120,
    "requireBlocksOnNewline": true,
    "requireCapitalizedConstructors": true,
    "requireCommaBeforeLineBreak": true,
    "requireCurlyBraces": [
        "for",
        "if",
        "switch",
        "try",
        "catch",
        "while",
        "with",
        "return",
        "function"
    ],
    "requireLineBreakAfterVariableAssignment": true,
    "requireLineFeedAtFileEnd": true,
    "requireMultipleVarDecl": true,
    "requireOperatorBeforeLineBreak": true,
    "requirePaddingNewlinesBeforeKeywords": [
        "for",
        "if",
        "switch",
        "try",
        "catch",
        "void",
        "while",
        "with",
        "return",
        "typeof",
        "function"
    ],
    "requirePaddingNewLineAfterVariableDeclaration": true,
    "requirePaddingNewLinesInObjects": true,
    "requireParenthesesAroundIIFE": true,
    "requireQuotedKeysInObjects": true,
    "requireSpaceAfterBinaryOperators": true,
    "requireSpaceAfterKeywords": [
        "for",
        "if",
        "else",
        "switch",
        "case",
        "try",
        "catch",
        "void",
        "while",
        "with",
        "return",
        "typeof"
    ],
    "requireSpaceAfterLineComment": true,
    "requireSpaceBeforeBinaryOperators": true,
    "requireSpaceBeforeBlockStatements": true,
    "requireSpaceBeforeKeywords": [
        "else",
        "catch",
        "while"
    ],
    "requireSpaceBeforeObjectValues": true,
    "requireSpaceBetweenArguments": true,
    "requireSpacesInAnonymousFunctionExpression": {
        "beforeOpeningCurlyBrace": true
    },
    "requireSpacesInConditionalExpression": true,
    "requireSpacesInForStatement": true,
    "requireSpacesInFunctionDeclaration": {
        "beforeOpeningCurlyBrace": true
    },
    "requireSpacesInFunctionExpression": {
        "beforeOpeningCurlyBrace": true
    },
    "requireSpacesInNamedFunctionExpression": {
        "beforeOpeningCurlyBrace": true
    },
    "validateIndentation": 4,
    "validateLineBreaks": "LF",
    "validateParameterSeparator": ", "
}
```

**Comment by mikesherov** [comment] 2015-04-08 19:32
Thanks for reporting! I'll look into this shortly!

**Comment by TheSavior** [comment] 2015-04-08 21:18
Duplicate of #1144

**Comment by mikesherov** [comment] 2015-04-09 13:11
Might not be exact duplicate unless you already investigated, @thesavior?

**Comment by TheSavior** [comment] 2015-04-09 13:56
It's an exact duplicate in the sense that I investigated enough to know that it was valiadateIndentation and added some tests that were failing that reproduced the problem for you to fix.

**Comment by mikesherov** [comment] 2015-04-09 14:02
OK, cool. Thanks @TheSavior !

**Closed by mikesherov** 2015-04-09 14:02 UTC
Labels: autofix

**Comment by lsjroberts** [comment] 2015-04-09 16:41
Thanks for the quick responses, I'll keep an eye on the other issue :)
