### ISSUE TITLE
Specify what parts of the programmatic API that are part of the public API

### ISSUE THREAD

**Issue by al-broco** [jscs-dev/node-jscs#1821] opened 2015-09-29 18:00 UTC
According to [semver](http://semver.org/), anything that is not part of the public API can change at any time, even between patch releases.

For projects that have a dependency on JSCS and that are using the programmatic interface it would be really useful to know what parts of that interface, if any, are part of the public API.

For example, in a project I am maintaining I am using the functions shown in the "Programmatic usage" section in the documentation. In addition, I am expecting a result from `checker.checkString(stringOfCode).getErrorList()` to return an array of objects with properties `message`, `line`, and `column` if applicable. The return value of `getErrorList` is not in the documentation, so I guess that in theory even a patch release of JSCS can break my application.

**Comment by hzoo** [comment] 2015-09-29 19:56
Are you getting a specific error? If it's the same as https://github.com/jscs-dev/node-jscs/issues/1816, then I think https://github.com/jscs-dev/node-jscs/commit/f12830a469959f3543c51bfc632fe37292ea6d09 should fix it - we will release a patch version since it was a regression (so I don't think that was intended)

**Comment by hzoo** [comment] 2015-09-30 01:02
Ok released 2.2.1

**Comment by al-broco** [comment] 2015-09-30 07:21
Sorry if I was unclear. This is a problem with the documentation, not the code, so there is no error.

I am wondering if it would be possible to add something to the documentation that clearly states what parts of the programmatic interface that are part of the public API? When I say "public API", I mean public  API according to the [http://semver.org](semver documentation):

"Software using Semantic Versioning MUST declare a public API. This API could be declared in the code itself or exist strictly in documentation. However it is done, it should be precise and comprehensive."

JSCS uses semver, and there is a section "Versioning & Semver" in the JSCS documentation with details.

For projects that have a dependency on JSCS and that use the programmatic interface it would be really useful to know what parts of the programmatic interface that are parts of the public API.

**Comment by hzoo** [comment] 2015-09-30 13:16
Ok I think https://github.com/jscs-dev/node-jscs/issues/1084 is similar - so at least those, but yeah that's certainly something that should be added.

**Comment by markelog** [comment] 2016-05-19 18:22
At this point only major and CST related bugs will be fixed.

**Closed by markelog** 2016-05-19 18:22 UTC
Labels: docs, internal
