### ISSUE TITLE
Proposal: use custom preset from file

### ISSUE THREAD

**Issue by lahmatiy** [jscs-dev/node-jscs#1595] opened 2015-07-31 10:47 UTC
We use our own code style across several projects. And we've got problem to synchronize config because some projects has some specific settings. So we want to use one file (as dependency of project) as base config with project specific extensions.
It's like how presets work. But for now `preset` accepts one of fixed list value only. It would be great if `preset` option could accept path to some file.
```json
{
    "preset": "path/to/base/config"
}
```

I (or anybody else) could implement it if there are no objections.

**Comment by mrjoelkemp** [comment] 2015-07-31 12:48
I believe you can do this as of 2.0. This commit by @markelog landed it: https://github.com/jscs-dev/node-jscs/pull/1150/files#diff-567cf572129c7869c556d43748ad5e63R104.

@markelog If you can confirm that this works as intended, we should definitely document this (powerful) feature.

**Comment by markelog** [comment] 2015-07-31 14:54
@lahmatiy Yeah, [see]((https://github.com/jscs-dev/node-jscs/releases/tag/v2.0.0)) the release notes for 2.0 "Simplified inclusion of plugins, presets, and custom rules" entry.

@mrjoelkemp yeah, we should - https://github.com/jscs-dev/node-jscs/pull/1597

**Comment by lahmatiy** [comment] 2015-07-31 15:56
@mrjoelkemp @markelog Yeah, I saw it in release notes and happy about it. But nothing found in documentation and went to see something about it in source code. But still nothing found in `config/configuration.js` and decided it was a mistake in release notes. Didn't know it placed in `config/node-configuration.js`.

Anyway it doesn't work as expected. When I use `.jscsrc` like this:

```json
{
    "preset": "./test.json"
}
```

I get warning: `Preset "test" does not extist`.

I see some progress on issue in #1597. But it has a restriction that path should has `.jscsrc` extension. I guess it isn't intuitive. And nothing about it in documentation :(

**Comment by markelog** [comment] 2015-07-31 16:18
> it was a mistake in release notes

If you found <b>anything</b> that is even looks like a mistake or inconsistency of some sort please don't hesitate to tell us.

> When I use .jscsrc like this:

Just checked, this should work, if issue persist would you mind create test repo?

>  see some progress on issue in #1597. 

Nuh, that pull provides ability to load presets with `.jscsrc` extension not just with `json` or `js`

**Comment by lahmatiy** [comment] 2015-07-31 16:56
> Just checked, this should work, if issue persist would you mind create test repo?

I figured out what the problem is. In my case `test.json` contains comments (as jscs allowed it in `.jscsrc`) and I suppose there is `JSON` parse error somewhere internal. But instead of related warning `jscs` outputs `Preset "test" does not extist`.

**Comment by markelog** [comment] 2015-08-02 17:15
Yeah that would be more correct way to do so, would you like to send us a PR?

**Comment by zxqfox** [comment] 2015-08-02 21:10
Why it not support comments if there is `.jscsrc` extension? Hum...

**Comment by markelog** [comment] 2015-08-02 21:15
It is supported

**Comment by lahmatiy** [comment] 2015-08-02 21:32
It's because `loadExternal` used to [load preset](https://github.com/jscs-dev/node-jscs/blob/master/lib/config/node-configuration.js#L111) content. And `loadExternal` uses `require`, which doesn't strip comments from JSON.

**Comment by iamstarkov** [comment] 2015-08-05 14:39
if this idea can extensed for shareble-configs concept like in eslint, it would be supercool

**Comment by markelog** [comment] 2015-08-05 15:48
@iamstarkov i'm confused, release notes clearly states that you can already do that, if there is any issues with the new functionality please let us now

**Closed** 2015-08-11 12:12 UTC
Labels: question
