### ISSUE TITLE
requireShorthandArrowFunctions matching multi-line returns

### ISSUE THREAD

**Issue by mikefrancis** [jscs-dev/node-jscs#2169] opened 2016-03-07 13:54 UTC
Hi,

I don't think this is _really_ a bug but would be good to clear something up.

I was working on a gulpfile this morning and thought I'd convert to use the ES2015 syntax to be in line with the rest of the codebase.

The jscs-linter for Atom kept squawking at one particular point (on the first line):

```javascript
gulp.task('js', () => {
  return browserify(config.src.root + '/' + config.src.js + '/script.js')
    .transform(babelify, { presets: ['es2015', 'react'] })
    .bundle()
    .pipe(source('script.js'))
    .pipe(gulp.dest(config.dist.root + '/' + config.dist.js));
});
```

```bash
error requireShorthandArrowFunctions Use the shorthand arrow function form
```

I understand why this is squawking; the gulp task is just returning one thing, so is trying to treat it as a one-liner.

* If I change to the shorthand arrow function syntax and move everything on to one line - the error goes away but it looks awful.
* If I make a variable and return that, instead of returning the whole thing - the error goes away again, but it seems unnecessary.

Was just wondering what your thoughts might be on this?

**Comment by hzoo** [comment] 2016-03-07 14:35
Hmm I guess this is just how the rule was written so not a bug but not people expect. If you look at the [source](https://github.com/jscs-dev/node-jscs/blob/80e8e414a26f55e250c4b3e3e109366a726776bd/lib/rules/require-shorthand-arrow-functions.js#L54-L58), it's pretty simple. We're just checking for a BlockStatement (use of `{}`) and then whether the only statement in the body is a return statement.

Not sure what we should do here. Yeah you could make a variable, or you could probably do

```js
gulp.task('js', () => 
  browserify(config.src.root + '/' + config.src.js + '/script.js')
    .transform(babelify, { presets: ['es2015', 'react'] })
    .bundle()
    .pipe(source('script.js'))
    .pipe(gulp.dest(config.dist.root + '/' + config.dist.js))
);
```

**Comment by mikefrancis** [comment] 2016-03-07 14:42
Thanks - yes, that would work. However, there's probably some other cases where people are using chain-able, "fluent" APIs and will need to return a value, so I imagine they will have the same problem.

For the moment I've just made a variable (which wasn't an issue at all), and will keep my eye on the changelogs and update if this is ever reimagined in the future.

**Comment by hzoo** [comment] 2016-03-07 14:43
Oh, part of the thing with the shorthand syntax is that it does automatically return the thing that's passed in.

**Comment by markelog** [comment] 2016-06-04 02:06
At this point only major and CST related bugs will be fixed.

**Closed by markelog** 2016-06-04 02:06 UTC
Labels: esnext, help-wanted, question
