### ISSUE TITLE
Conflict between two rules because function* is not considered as a keyword

### ISSUE THREAD

**Issue by Skywalker13** [jscs-dev/node-jscs#2185] opened 2016-03-22 07:26 UTC
In the case of a jscsrc config file with : 

```js
{
  "requireSpaceAfterKeywords": true,
  "disallowSpacesInGenerator": { "beforeStar": true }
}
```
```js
function* foobar() {}
```
Then `requireSpaceAfterKeywords` returns an error.

But IMHO `function*` should be considered as a keyword and not only `function`.

**Comment by markelog** [comment] 2016-03-28 12:44
Duplicate of https://github.com/jscs-dev/node-jscs/issues/2168

**Closed by markelog** 2016-03-28 12:44 UTC
